config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "pages#home"
  root "gnomes#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :gnomes do
    resources :bookings, only: [:create, :destroy]
  end

  # resources :users do
  #   resources :gnomes, only: :index
  #   # users/:id/gnomes
  # end

  get "mygnomes", to: "pages#mygnomes"
  get "mybookings", to: "pages#mybookings"
  get "meettheteam", to: "pages#meettheteam"
  get "aboutgarden", to: "pages#aboutgarden"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :gnome
  belongs_to :user

  validates :booking_date, presence: true
end

app/models/gnome.rb
class Gnome < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user

  validates :name, :description, :price, presence: true
  validates :name, uniqueness: true
end

app/models/gnomes_owner.rb
class GnomesOwner < ApplicationRecord
  belongs_to :gnome
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :gnomes
  # SELECT gnomes.* FROM users JOIN gnomes ON users.id= gnomes.user_id

  has_many :booked_gnomes, through: :bookings, source: 'gnome'
  # SELECT gnomes.* FROM users JOIN bookings ON bookings.user_id = users.id JOIN gnomes ON bookings.gnome_id = gnomes.id

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @gnome = Gnome.find(params[:gnome_id])
    @booking.gnome = @gnome
    @booking.user = current_user

    if @booking.save
      redirect_to mybookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to mybookings_path, status: :see_other
  end

  def booking_params
    params.require(:booking).permit(:booking_date)
  end
end

app/controllers/gnomes_controller.rb
class GnomesController < ApplicationController
  def index
      @gnomes = Gnome.all
  end

  def show
    @gnome = Gnome.find(params[:id])
    @booking = Booking.new
  end

  def new
    @gnome = Gnome.new
  end

  def create
    @gnome = Gnome.new(gnome_params)
    @gnome.user = current_user
    if @gnome.save
      redirect_to mygnomes_path
    else
      render :new, status: :unprocessable_entity
    end
  end


  def edit
    @gnome = Gnome.find(params[:id])
  end

  def update
    @gnome = Gnome.find(params[:id])
    @gnome.update(gnome_params)
    # No need for app/views/restaurants/update.html.erb
    redirect_to mygnomes_path
  end

  def destroy
    @gnome = Gnome.find(params[:id])
    @gnome.destroy
    redirect_to mygnomes_path, status: :see_other, notice: 'Gnome was successfully deleted.'
  end

  private

  def gnome_params
    params.require(:gnome).permit(:name, :description, :price, :image_path)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def mygnomes
    @gnomes = Gnome.where(user:current_user)
  end

  def mybookings
    @bookings = Booking.where(user:current_user)

    # user = current_user
    # @bookings = user.bookings
  end

  def meettheteam
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gnomes/edit.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('<%= asset_path('banner.jpg')%>');">
  <h1>Edit Gnome Details</h1>
</div>

<%= simple_form_for(@gnome) do |f|%>

  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :image_path %>
  <%= f.submit "Submit Gnome", class: "btn-green btn-green-gnome-card" %>
<% end %>

app/views/gnomes/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('<%= asset_path('banner.jpg')%>');">
  <h1>Welcome to Garden Gnome.</h1>
</div>

  <div class="grid_container">
    <% @gnomes.each do |gnome| %>
        <div class="card">
          <% if gnome.image_path.present? %>
            <%= image_tag(gnome.image_path, class: "card-img-top") %>
          <% else %>
            <%= image_tag("logo.png", class: "card-img-top") %>
          <% end %>

          <div class="card-body">
            <h5 class="card-title"><%= gnome.name %></h5>
            <p class="card-text"><%= gnome.description %></p>
            <h5 class="card-title">£ <%= gnome.price %></h5>
            <div class="d-flex justify-content-end mt-3">
              <%= link_to 'Book Me', gnome_path(gnome), class: "btn-green-gnome-card btn-green"%>
            </div>
          </div>
        </div>
    <% end %>
  </div>

app/views/gnomes/new.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('<%= asset_path('banner.jpg')%>');">
  <h1>Add a new Gnome</h1>
</div>
<%= simple_form_for @gnome do |f| %>
<%= f.input :name, placeholder: "Your gnome's name:" %>
<%= f.input :description, placeholder: "A few words about your gnome:" %>
<%= f.input :price, placeholder: "What would you like to charge?" %>
<%= f.input :image_path, placeholder: "Upload your image:" %>
<%= f.submit "Submit Gnome", class: "btn-green btn-green-gnome-card" %>
<% end %>

app/views/gnomes/show.html.erb
<div class="show_container d-flex justify-content-center">

<div class="col-8 show_card">
  <div class="card mb-4">
    <div class="card-body">
      <%= image_tag(@gnome.image_path, class: "card-img-top") %>
      <h5 class="card-title"><%= @gnome.name %></h5>
      <p class="card-text"><%= @gnome.description %></p>
      <h5 class="card-title">£ <%= @gnome.price %></h5>
      <h4><%= @gnome.name %> has been booked for: </h4>
      <ul>
        <% if @gnome.bookings.length > 0 %>
          <% @gnome.bookings.each do |booking| %>
            <li><%= booking.booking_date %></li>
          <% end %>
        <% else %>
          <li>Be the first to make a booking!</li>
        <% end %>
      </ul>
      Book me here
      <div class="d-flex align-items-center">
        <%= simple_form_for [@gnome, @booking], html: { class: "inline-form" } do |f| %>
          <%= f.input :booking_date, input_html: { class: "inline-input" }, label: false %>
          <%= f.submit "Create booking :D", class: "mb-3 btn-green inline-submit btn-green-gnome-card" %>
        <% end %>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GnomeGarden</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="icon" href="<%= asset_path('favicon-32x32.png') %>" type="image/x-icon">
    <link rel="shortcut icon" href="<%= asset_path('favicon-32x32.png') %>" type="image/x-icon">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
    <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/aboutgarden.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('<%= asset_path('banner.jpg')%>');">
  <h1>About the Garden</h1>
</div>

<div class="about_text">
  <p>Welcome to Garden Gnome, the only app where renting a tiny bearded lawn guardian makes perfect sense!</p>
  <p>Need to spruce up your yard? Want to freak out your neighbors?</p>
  <p>Or maybe you just want someone who'll listen to your problems without judging (because, you know, they’re made of ceramic).</p>
  <p>Whatever the reason, our gnomes are here to gnome-ify your life!</p>
  <p>Choose from a variety of delightful, slightly creepy garden gnomes that are ready to stand awkwardly in your yard.</p>
  <p>Because honestly, why wouldn’t you want a weird little guy silently judging your lawn care skills?</p>
</div>

<div class="d-flex align-content-center justify-content-center">
  <div class="about_img">
    <%= image_tag "logo.png" %>
  </div>
  <div class="about_img">
    <%= image_tag "logo.png" %>
  </div>
  <div class="about_img">
    <%= image_tag "logo.png" %>
  </div>
  <div class="about_img">
    <%= image_tag "logo.png" %>
  </div>
  <div class="about_img">
    <%= image_tag "logo.png" %>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/meettheteam.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('<%= asset_path('banner.jpg')%>');">
  <h1>Meet the Team</h1>
</div>
<div class="profile_container">
  <div class="founders-card">
    <div>
      <%= image_tag("founder01.jpeg", class: "founders-card-img") %>
    </div>
    <div>
      <h2>Claudia Kwok</h2>
      <h3>Software Engineer</h3>
      <h4>UK</h4>
      <p>Aspiring to drive product development through people-centered AI solutions that deliver meaningful, positive impact.</p>
    </div>
  </div>

  <div class="founders-card">
    <div>
      <%= image_tag("founder02.jpeg", class: "founders-card-img") %>
    </div>
    <div>
      <h2>Damien Baubriau</h2>
      <h3>Software Engineer</h3>
      <h4>UK</h4>
      <p>Transitioning to Full-Stack Development, I leverage my sales experience, technical skills, and problem-solving mindset to grow as a software developer while applying my customer-focused approach to web development.</p>
    </div>
  </div>

  <div class="founders-card">
    <div>
      <%= image_tag("founder03.jpeg", class: "founders-card-img") %>
    </div>
    <div>
      <h2>Szymon Niedorezo</h2>
      <h3>Software Engineer</h3>
      <h4>UK</h4>
      <p>Hello I'm Simon. Aspiring web developer based in Cornwall.</p>
    </div>
  </div>

  <div class="founders-card">
    <div>
      <%= image_tag("founder04.jpeg", class: "founders-card-img") %>
    </div>
    <div>
      <h2>Joshua Banjo</h2>
      <h3>Software Engineer</h3>
      <h4>UK</h4>
      <p>Backend Engineer with a product focus and passion for building robust, scalable APIs in high growth start ups.</p>
    </div>
  </div>
</div>

app/views/pages/mybookings.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('<%= asset_path('banner.jpg')%>');">
  <h1>My Gnome Bookings</h1>
</div>

<div class="grid_container">

    <% if @bookings.length > 0 %>
      <% @bookings.each do |booking| %>
        <div class="card">
        <%= image_tag(booking.gnome.image_path, class: "card-img-top") %>
          <div class="card-body">
            <li><%= booking.gnome.name %></li>
            <li><%= booking.gnome.description %></li>
            <li>£<%= booking.gnome.price %></li>
            <li><%= booking.booking_date %></li>
            <li>You can reach the owner of the Gnome here: <%= booking.gnome.user.email %></li>
            <div class="d-flex justify-content-end mt-3"><%= link_to "Cancel your booking", gnome_booking_path(booking.gnome, booking), class: "btn-green-gnome-card btn-green mt-2", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></div>
          </div>
        </div>
      <% end %>
    <% else %>
      <li>You don't have any bookings yet - go and grab a Gnome XD</li>
    <% end %>

</div>

app/views/pages/mygnomes.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('<%= asset_path('banner.jpg')%>');">
  <h1>My Gnomes</h1>
</div>

<div class="grid_container">
    <% @gnomes.each do |gnome| %>
        <div class="card">
          <% if gnome.image_path.present? %>
            <%= image_tag(gnome.image_path, class: "card-img-top") %>
          <% else %>
            <%= image_tag("logo.png", class: "card-img-top") %>
          <% end %>

          <div class="card-body">
            <h5 class="card-title"><%= gnome.name %></h5>
            <p class="card-text"><%= gnome.description %></p>
            <h5 class="card-title">£ <%= gnome.price %></h5>
            <div class="d-flex justify-content-between mt-3">
              <%= link_to 'Check me', gnome_path(gnome), class: "btn-green-gnome-card btn-green" %>
              <%= link_to 'Edit', edit_gnome_path(gnome), class: "btn-green-gnome-card btn-green" %>
              <%= link_to 'Delete', gnome_path(gnome), class: "btn-green btn-red-gnome-card", data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website is made with <i class="fas fa-heart"></i> by Damien, Szymon, Claudia and Joshua.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to gnomes_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
      <span class="logo-text"> Garden Gnome </span>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Add my Gnome", new_gnome_path, class: "nav-link btn-green btn-navbar" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Meet the team", meettheteam_path, class: "nav-link btn-green btn-navbar" %>
          </li>
          <li class="nav-item active">
            <%= link_to "About the Garden", aboutgarden_path, class: "nav-link btn-green btn-navbar" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Gnomes", mygnomes_path, class: "dropdown-item" %>
              <%= link_to "My Bookings", mybookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
              <%# link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>